### ISSUE TITLE
Test on Human36M dataset - different results

### ISSUE THREAD

**Issue by SimicCh** [zhezh/adafuse-3d-human-pose#10]
Hi, 
nice approach for 3D Human Poseestimation.
I tried to reproduce your results on Human36M dataset by using ./experiments/h36m/h36m_4view.yaml configuration and your pretrained models. (h36m_4view.pth.tar and h36m_4view_d87025.pth.tar)
The evaluation results are worse than specified in your description as you see below:
MPJPE summary: j3d_NoFuse 30.95
MPJPE summary: j3d_HeuristicFuse 29.24
MPJPE summary: j3d_ScoreFuse 28.52
MPJPE summary: j3d_ransac 30.04
MPJPE summary: j3d_AdaFuse 28.05

Are the uploaded pretrained models the final state or did you use another state for your evaluation?

Thank you!

**Comment by zhezh** [comment]
The results are same as in #8 . Could you please check if you missed any process?

**Comment by SimicCh** [comment]
Hi, thank you for your reply, it's solved. It was the same issue as in #2.
