### ISSUE TITLE
About the pretrained models

### ISSUE THREAD

**Issue by cannotseeme** [zhezh/adafuse-3d-human-pose#12]
Hi! Really appreciated for the research. I followed the instructions to setup for the model and loaded the pretrained models successfully. Howerver, the metrics I acquired were far away from the metrics reported. Does anyone encountered with the same problem? Thanks.
![~VA3IBLPD`COMLJ{6`} O}X](https://github.com/zhezh/adafuse-3d-human-pose/assets/75235320/9de7da8e-86ab-42ca-b59f-451d81e0bb51)

**Comment by zhezh** [comment]
#2 might help

**Comment by cannotseeme** [comment]
> #2 might help

Thanks a lot!
