### ISSUE TITLE
Training for Panoptic dataset

### ISSUE THREAD

**Issue by Mayy1994** [zhezh/adafuse-3d-human-pose#7]
Thank you for sharing this great work.

I noticed that the CMU Panoptic Dataset used in the paper is not the regular Panoptic dataset, but the training and testing sequences which consist of only one person. 
I have downloaded this dataset (270G from http://domedb.perception.cs.cmu.edu/mtc.html).
Could you please share the training code of AdaFuse for this dataset? Many thanks in advance!!

**Comment by zhezh** [comment]
@Mayy1994  You may add a dataset class for Panoptic. https://github.com/microsoft/voxelpose-pytorch/blob/main/lib/dataset/panoptic.py provides a practical template.

**Comment by Mayy1994** [comment]
Thank you for your reply. 

In your AdaFuse paper, Figure 14 shows the mean 3D pose errors on Panoptic when different numbers of cameras are used. 
Could you please give me the details of the camera ID used for 3 Views, 4 Views, 5 Views, and 6 Views, respectively?
I would like to conduct the experiments with the same camera settings for fair comparisons.

Thank you very much!

**Comment by zhezh** [comment]
the 4views and 6views configurations are [1, 2, 10, 13] and [1, 2, 3, 10, 13, 23]. However, I could not find the 3 and 5 view config 😂

**Comment by Mayy1994** [comment]
Thank you so much. I will try these camera configurations first.

If you find the 3 and 5 views config later, please tell me at your earliest convenience. Many thanks~~
